#!/bin/sh /etc/rc.common

. "${IPKG_INSTROOT}/usr/lib/amx/scripts/amx_procd_init_functions.sh"

START=99
USE_PROCD=1

name="prplmesh"
datamodel_root="Device.WiFi.DataElements."

start_service() {
    register_service "$name" "${IPKG_INSTROOT}/opt/prplmesh/scripts/prplmesh_utils.sh" run
}

stop_service() {
    deregister_service "$name"
}
