#!/bin/sh /etc/rc.common

NAME=prplmesh

###########################################
# 1. Helper functions - Wi-Fi Operations
###########################################

__wlan_reset__() {
    wifi down
    sleep 5
    local leftover_processes="$(ps | grep '[h]ostapd\|[s]upp')"
    if [ -n "$leftover_processes" ]; then
        logger -t "${NAME}" -p daemon.warn "Wlan procceses still running after wifi down: $leftover_processes"
        echo "Wlan procceses still running after wifi down: $leftover_processes"
        # STA interfaces/processes sometimes not closed properly (https://jira.prplfoundation.org/browse/PPM-1778)
        # This issue was spotted after wifi driver release update UGW8.5.2 in prplos.
        # Currently just log this event and continue.
        # In case wlan will not recover wlan_ready() will handle it.
    fi
    wifi up
}

__hostapd_ready__() {
    hostapd_cli -i$1 stat &>/dev/null
}

__pwhm_ready__() {
    ba-cli Device.WiFi.Radio.?0 &>/dev/null
}

__get_radio_names__() {
    ba-cli -l "WiFi.Radio.*.Name?"
}

__all_wlan_ready__() {
    for iface in "$(__get_radio_names__)"; do
        if ! __hostapd_ready__ "$iface"; then
            logger -t "${NAME}" -p daemon.warn "$0: wlan $iface not ready"
            return 1
        fi
    done
}

__wait_for_all_wlan_ready__() {
    local delay=${1-3}
    local timeout=60

    start_time="$(date -u +%s)"
    while true; do
        if ! __pwhm_ready__; then
            break
        fi

        if ! __all_wlan_ready__; then
            break
        fi

        end_time="$(date -u +%s)"
        elapsed="$(($end_time - $start_time))"
        if [ "$elapsed" -gt "$timeout" ]; then
            return 1
        fi

        sleep $delay
    done
}

#############################
# 2. UCI Service functions
#############################

__uci_set_repeater_mode__() {
    uci set prplmesh.config.management_mode='Multi-AP-Agent'
    uci set prplmesh.config.operating_mode='WDS-Repeater'
    uci commit prplmesh
}

__uci_set_gateway_mode__() {
    uci commit network
    uci set prplmesh.config.management_mode='Multi-AP-Controller-and-Agent'
    uci set prplmesh.config.operating_mode='Gateway'
    uci commit prplmesh
}

__uci_set_certification_mode__() {
    uci set prplmesh.config.certification_mode=1
    uci commit prplmesh
}

#############################
# 3. Main Service Operations
#############################

__start__() {
    logger -t "${NAME}" -p daemon.info "Start prplMesh"

    # Waiting for all WLAN ifaces to become ready
    __wait_for_all_wlan_ready__ || {
        logger -t "${NAME}" -p daemon.warn "Timeout waiting for WLAN ready!"
        exit 1
    }

    # TODO: change to use `management_mode`
    # for now it was decided to keep it as it is until FEAT-27
    if [ "$(uci get prplmesh.config.operating_mode)" = "Gateway" ]; then
        logger -t "${NAME}" -p daemon.info "Start prplMesh controller & agent"
        /opt/prplmesh/scripts/prplmesh_utils.sh start -m CA
    else
        logger -t "${NAME}" -p daemon.info "Start prplMesh agent"
        /opt/prplmesh/scripts/prplmesh_utils.sh start -m A
    fi
}

__stop__() {
    logger -t "${NAME}" -p daemon.info "Stop prplMesh"

    /opt/prplmesh/scripts/prplmesh_utils.sh stop

    # since prplmesh changes the wifi runtime configuration,
    # restart wifi when stopping prplmesh
    # unless using prplmesh wireless hardware manager
    ba-cli Device.WiFi.Radio.?0 &>/dev/null || __wlan_reset__
}

__restart__() {
    logger -t "${NAME}" -p daemon.info "Restart prplMesh"

    # prplmesh_utils do the same for 'restart' option (restart = stop & start),
    # but does not wait for wlan ifaces to become ready,
    # so it's needed to do this manually
    __stop__
    __start__
}

__status__() {
    # Show if radios are enabled
    for radio_name in $(__get_radio_names__); do
        enabled=$(ba-cli -l "WiFi.Radio.[Name == \"$radio_name\"].Enable?")
        if [ "$enabled" -eq 1 ]; then
            echo "$radio_name is enabled"
        else
            echo "$radio_name is disabled"
        fi
    done

    # prplMesh configuration status
    echo "management_mode: $(uci get prplmesh.config.management_mode)"
    echo "operating_mode: $(uci get prplmesh.config.operating_mode)"
    __all_wlan_ready__ && echo "WLAN Ready" || echo "WLAN not ready"
    /opt/prplmesh/scripts/prplmesh_utils.sh status
}

__repeater_mode__() {
    __stop__
    __uci_set_repeater_mode__
    __start__
    echo "prplmesh repeater mode set"
}

__gateway_mode__() {
    __stop__
    __uci_set_gateway_mode__
    __start__
    echo "prplmesh gateway mode set"
}

__certification_mode__() {
    mode=${1-gateway} # gateway by default

    __stop__
    case "$mode" in
    controller | gateway | controller_mode | gateway_mode)
        __uci_set_gateway_mode__
        __uci_set_certification_mode__
        ;;
    agent | repeater | agent_mode | repeater_mode)
        __uci_set_repeater_mode__
        __uci_set_certification_mode__
        ;;
    esac
    __start__
}

##################
# 3. Entry Points
##################

start() { __start__; }
stop() { __stop__; }
restart() { __restart__; }
status() { __status__; }
repeater_mode() { __repeater_mode__; }
gateway_mode() { __gateway_mode__; }
certification_mode() { __certification_mode__; }

#############################
# 4. Extra Commands and Help
##############################

EXTRA_COMMANDS="status repeater_mode gateway_mode certification_mode"
EXTRA_HELP='''
	status                    show service status
	certification_mode <mode> set certification controller mode
	repeater_mode [backhaul]  set repeater mode with backhaul wired (default) or wireless
	gateway_mode              set gateway mode
'''
